version: '3'
services:
  golang-app:
    image: hexsatisfaction_purchase:1.0  # Replace with your Go application image
    container_name: hexsatisfaction_purchase
    restart: always
    ports:
      - 7071:8080
    environment:
      - MONGO_HOST=hexsatisfaction_purchase_mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=hexsatisfaction_purchase
      - MONGO_DATABASE_DIALECT=mongodb
      - JWT_SIGNING_KEY=some_key
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - HTTP_MAX_HEADER_BYTES=1000
      - HTTP_READ_TIMEOUT=10s
      - HTTP_WRITE_TIMEOUT=10s
      - GRPC_HOST=hexsatisfaction
      - GRPC_PORT=9090

  mongo:
    image: mongo:latest
    container_name: hexsatisfaction_purchase_mongo
    environment:
      - MONGO_DATABASE_NAME=hexsatisfaction_purchase
      - MONGO_DATABASE_DIALECT=mongodb
