// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/JesusG2000/hexsatisfaction_purchase/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Comment is an autogenerated mock type for the Comment type
type Comment struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *Comment) Create(ctx context.Context, request model.CreateCommentRequest) (string, error) {
	ret := _m.Called(ctx, request)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateCommentRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.CreateCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, request
func (_m *Comment) Delete(ctx context.Context, request model.DeleteCommentRequest) (string, error) {
	ret := _m.Called(ctx, request)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, model.DeleteCommentRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.DeleteCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *Comment) FindAll(ctx context.Context) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context) []model.CommentDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByUserID provides a mock function with given fields: ctx, request
func (_m *Comment) FindAllByUserID(ctx context.Context, request model.UserIDCommentRequest) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.UserIDCommentRequest) []model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UserIDCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, request
func (_m *Comment) FindByID(ctx context.Context, request model.IDCommentRequest) (*model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.IDCommentRequest) *model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.IDCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPeriod provides a mock function with given fields: ctx, request
func (_m *Comment) FindByPeriod(ctx context.Context, request model.PeriodCommentRequest) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.PeriodCommentRequest) []model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.PeriodCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPurchaseID provides a mock function with given fields: ctx, request
func (_m *Comment) FindByPurchaseID(ctx context.Context, request model.PurchaseIDCommentRequest) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.PurchaseIDCommentRequest) []model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.PurchaseIDCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByText provides a mock function with given fields: ctx, request
func (_m *Comment) FindByText(ctx context.Context, request model.TextCommentRequest) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.TextCommentRequest) []model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.TextCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIDAndPurchaseID provides a mock function with given fields: ctx, request
func (_m *Comment) FindByUserIDAndPurchaseID(ctx context.Context, request model.UserPurchaseIDCommentRequest) ([]model.CommentDTO, error) {
	ret := _m.Called(ctx, request)

	var r0 []model.CommentDTO
	if rf, ok := ret.Get(0).(func(context.Context, model.UserPurchaseIDCommentRequest) []model.CommentDTO); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UserPurchaseIDCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *Comment) Update(ctx context.Context, request model.UpdateCommentRequest) (string, error) {
	ret := _m.Called(ctx, request)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, model.UpdateCommentRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UpdateCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
